### ISSUE TITLE
Error with systemd ExecStart= setting

### ISSUE THREAD

**Issue by dbenaben** [robertdebock/ansible-role-gitlab_runner#1]
Error with gitlab-runner systemd unit (drop-in file) and `ExecStart=` setting

## Bug

After reloaded systemd manager (usefull to load new drop-in file)
```
systemctl daemon-reload
```

Restart gitlab-runner.service failed with:
```
systemd[1]: gitlab-runner.service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.
```

## Environment

* CentOS Linux release 7.6.1810 (Core) 
* systemd 219

---

Thanks for your work

**Comment by robertdebock** [comment]
Thanks or the creating the issue. I've merged [your pull request](https://github.com/robertdebock/ansible-role-gitlab_runner/pull/2)  and released [1.4.2](https://github.com/robertdebock/ansible-role-gitlab_runner/releases/tag/1.4.2).

Thanks for helping!
